######################################################################
# Automatically generated by qmake (2.01a) mar. juil. 2 19:24:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.hpp gotocelldialog.h sortdialog.h
FORMS += gotocelldialog.ui sortdialog.ui
SOURCES += finddialog.cpp gotocelldialog.cpp main.cpp sortdialog.cpp
